import { Fruit } from './fruit';

export const FRUITS: Fruit[] = [
    { id: 1, name: 'Apple' },
    { id: 2, name: 'Banana' },
    { id: 3, name: 'Cherry' },
    { id: 4, name: 'Coconut' },
    { id: 5, name: 'Cranberry' },
    { id: 6, name: 'Goji berry' },
    { id: 7, name: 'Lemon' },
    { id: 8, name: 'Mango' },
    { id: 9, name: 'Melon' },
    { id: 10, name: 'Yuzu' },
    { id: 11, name: 'Orange' },
    { id: 12, name: 'Papaya' },
    { id: 13, name: 'Peach' },
    { id: 14, name: 'Pineapple' },
    { id: 15, name: 'Pomelo' },
    { id: 16, name: 'Yuzu' },
    { id: 17, name: 'Orange' },
    { id: 18, name: 'Papaya' },
    { id: 19, name: 'Peach' },
    { id: 20, name: 'Pineapple' },
    { id: 21, name: 'Pomelo' },
    { id: 22, name: 'Pomelo' },
    { id: 23, name: 'Yuzu' },
    { id: 24, name: 'Orange' },
    { id: 25, name: 'Papaya' },
    { id: 26, name: 'Peach' },
    { id: 27, name: 'Pineapple' },
    { id: 28, name: 'Pomelo' },
    { id: 29, name: 'Pineapple' },
    { id: 30, name: 'Pomelo' },
  ];